id: I4162DF20
legacy_id: P004327
ocr_import_info:
  bdrc_scan_id: W1KG17112
  source: bdrc
  ocr_info:
    timestamp: '2020-03-26T08:28:15'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-31T09:30:54.985736+00:00'
last_modified: 2022-08-31 17:31:32.050105
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1KG17112
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1KG17112
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདུལ་འགྲེལ་བློ་གསར་འཇུག་ངོགས་གསེར་གྱི་ཐེམ་སྐས།
  author: ཕ་ར་དགེ་བཤེས་རྣམ་རྒྱལ་དབང་ཆེན།
statistics:
  ocr_word_mean_confidence_index: 0.8079215007739197
  ocr_word_median_confidence_index: 0.9700000286102295
quality: null
bases:
  I1KG17123:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17123
      total_pages: 510
      volume_number: 2
      volume_pages_bdrc_intro: 2
    order: 2
    base_file: I1KG17123.txt
    statistics:
      ocr_word_median_confidence_index: 0.9700000286102295
      ocr_word_mean_confidence_index: 0.793086935688842
    legacy_id: v002
  I1KG17122:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1KG17122
      total_pages: 516
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1KG17122.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.8221199974395547
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
