id: I4162DF20
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-26T08:31:52+00:00'
last_modified: '2022-06-07T22:01:19.690420+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG17112
  title: འདུལ་འགྲེལ་བློ་གསར་འཇུག་ངོགས་གསེར་གྱི་ཐེམ་སྐས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '1411':
      image_group_id: I1KG17122
      title: ''
      total_pages: 516
      order: 1
      base_file: 1411.txt
    C41B:
      image_group_id: I1KG17123
      title: ''
      total_pages: 510
      order: 2
      base_file: C41B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
